# Generated by Django 5.2.6 on 2025-09-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_before_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
