# Generated by Django 5.2.6 on 2025-09-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('item_specific', 'Item Specific')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('max_uses_per_customer', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specific_items', models.ManyToManyField(blank=True, related_name='discounts', to='menu.menuitem')),
            ],
        ),
    ]
